### ISSUE TITLE
[request] Option to skip source/target duplicate detection

### ISSUE THREAD

**Issue by eleius** [Ambrevar/hsync#1]
"Source duplicate" and "target duplicate" detection seem to slow down hsync's operation considerably - I'm not sure if there is extra processing going on (or if it's part of the normal copy routine). In that case I'd like to request a parameter to disable the detection as I want to keep the duplicates.

**Comment by Ambrevar** [comment]
hsync does not copy anything, it only moves things around.

hsync performs an analysis to know which files are identical before being sure it's moving the right things around.The duplicates are detected as a side-effect of the analysis: they don't cost anything extra.

See https://godoc.org/gitlab.com/ambrevar/hsync for the implementation details.

Let me know if I misunderstood your request.

By the way, the project has been moved to https://gitlab.com/ambrevar/hsync.

**Comment by eleius** [comment]
Thanks for your explanation.
